### ISSUE TITLE
API issue with Bittrex

### ISSUE THREAD

**Issue by Netzarim** [DeviaVir/zenbot#1085]
---------------------------------------- STARTING LIVE TRADING ----------------------------------------
Press  l  to list available commands.
Web GUI running on http://x.x.x.x:20009/
APIKEY_INVALID
please note: the bittrex api does not support backfilling (trade/paper only).
please note: make sure to set the --period_length=1m to make sure data for trade/paper is fetched.
APIKEY_INVALID
/root/zenbot/commands/trade.js:506
                throw new Error('Error during syncing balance. Please check your API-Key')
                ^

Error: Error during syncing balance. Please check your API-Key
    at /root/zenbot/commands/trade.js:506:23
    at /root/zenbot/lib/engine.js:203:13
    at /root/zenbot/extensions/exchanges/bittrex/exchange.js:170:9
    at Request._callback (/root/zenbot/node_modules/node.bittrex.api/node.bittrex.api.js:114:25)
    at Request.self.callback (/root/zenbot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/zenbot/node_modules/request/request.js:1060:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/zenbot/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

I have gone into Bittrex and verified the API key and secret and they are as listed.

**Comment by Netzarim** [comment]
Running with --paper has no error...

**Comment by Netzarim** [comment]
---------------------------------------- STARTING LIVE TRADING ----------------------------------------
Press  l  to list available commands.
/root/zenbot/extensions/exchanges/gdax/exchange.js:54
        throw new Error('please configure your GDAX credentials in conf.js')
        ^

Error: please configure your GDAX credentials in conf.js
    at authedClient (/root/zenbot/extensions/exchanges/gdax/exchange.js:54:15)
    at Object.getBalance (/root/zenbot/extensions/exchanges/gdax/exchange.js:157:20)
    at Object.syncBalance (/root/zenbot/lib/engine.js:192:18)
    at Object.<anonymous> (/root/zenbot/commands/trade.js:399:24)
    at Immediate._onImmediate (/root/zenbot/node_modules/sosa/api.js:15:12)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)


It appears that maybe the current version isn't pulling the conf.js properly... I have it in the same folder...

**Comment by Netzarim** [comment]
I found an error.. Mine... in the conf.js file when i explicitly called it.  I corrected the error, and it appears to be working now

**Comment by brucetus** [comment]
@Netzarim What did you change in your conf.js? My API key is correct and i still get this error
